apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master-deployment
  labels:
    app: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
        - name: jenkins-master
          image: jenkins
          env:
            - name: JAVA_OPTS
              value: >-
                -Dcom.sun.management.jmxremote.rmi.port=9010
                -Dcom.sun.management.jmxremote=true
                -Dcom.sun.management.jmxremote.port=9010
                -Dcom.sun.management.jmxremote.ssl=false
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.local.only=false
                -Djava.rmi.server.hostname=127.0.0.1
          ports:
            - name: http-port
              containerPort: 8080
            - name: jmx-port
              containerPort: 9010
